### ISSUE TITLE
TypeError: plugins.expectFile is not a function

### ISSUE THREAD

**Issue by shivampmc** [bobmotor/magento-2-gulp#23]
I found this tool today and when I tried I got this error. Is it something that I am doing wrong?

[16:23:20] Using gulpfile C:\xampp\htdocs\m2\gulpfile.js
[16:23:20] Starting 'critical'...
Running gulp task Critical CSS compilation for 1 theme(s):
pmcArceus
[16:23:20] 'critical' errored after 17 ms
[16:23:20] TypeError: plugins.expectFile is not a function
    at C:\xampp\htdocs\m2\dev\tools\gulp\tasks\critical.js:44:31
    at Array.forEach (<anonymous>)
    at module.exports (C:\xampp\htdocs\m2\dev\tools\gulp\tasks\critical.js:41:36)
    at critical (C:\xampp\htdocs\m2\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:413:15)
    at runBound (domain.js:424:12)
    at asyncRunner (C:\xampp\htdocs\m2\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by volodymyr-lisniak** [comment]
@shivampmc which gulp version are you using?
Show me your `gulp -v` and `node -v`

**Comment by congson95dev** [comment]
I've faced this issue last week, and this is because package.json in root folder of project are not paste correct from this git.
![image](https://user-images.githubusercontent.com/33352529/136342935-48c1e79b-a98e-440e-8531-d7406dd8e970.png)
All of this gulp was never come to my package.json
Here's my package.json, it don't have gulp at all.
![image](https://user-images.githubusercontent.com/33352529/136343220-8da820a9-1179-4307-8b00-a1f655a1458e.png)
To solve this problem, i backup that package.json to package.json.bak then run as normal. Maybe you could try manual copy all gulp to package.json then run again.

**Comment by volodymyr-lisniak** [comment]
@saxsax1995 You won't have `package.json` content from this git repository.
It would help if you did this manually.

From `README.md`:
<img width="877" alt="package json" src="https://user-images.githubusercontent.com/9715167/137190932-2569c0b3-c7f7-49fe-a2d6-2502ea27ffa8.png">
